name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Extract version from tag
      id: get_version
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo "Extracted version: $TAG"
        echo "version=$TAG" >> $GITHUB_OUTPUT

    - name: Clean output directories
      run: |
        rm -rf ./nupkgs
        mkdir -p ./nupkgs

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Pack NuGet package
      run: |
        dotnet pack src/MediaHub/MediaHub.csproj \
          --configuration Release \
          -p:Version=${{ steps.get_version.outputs.version }} \
          --no-build \
          --output ./nupkgs

    - name: Check generated packages
      run: ls -lh ./nupkgs

    - name: Push package to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg \
             --api-key ${{ secrets.NUGET_API_KEY }} \
             --source https://api.nuget.org/v3/index.json
