name: Publish MediaHub.Contracts to NuGet

on:
  push:
    tags:
      - "contracts-v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Clean output directories
        run: |
          rm -rf ./nupkgs
          mkdir -p ./nupkgs

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/contracts-v}
          dotnet pack src/MediaHub.Contracts/MediaHub.Contracts.csproj --configuration Release -p:Version=$TAG_VERSION --no-build --output nupkgs

      - name: Check package version
        run: |
          echo "Generated packages:"
          ls -la ./nupkgs

      - name: Push to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
